feat: Support ARM64

diff --git a/build/virt-prerunner/Dockerfile b/build/virt-prerunner/Dockerfile
--- a/build/virt-prerunner/Dockerfile
+++ b/build/virt-prerunner/Dockerfile
@@ -16,9 +16,23 @@ FROM alpine
 
 RUN apk add --no-cache tini curl screen dnsmasq cdrkit iptables
 
-RUN curl -sLo /usr/bin/cloud-hypervisor https://github.com/cloud-hypervisor/cloud-hypervisor/releases/download/v24.0/cloud-hypervisor-static && chmod +x /usr/bin/cloud-hypervisor
-RUN mkdir /var/lib/cloud-hypervisor && curl -sLo /var/lib/cloud-hypervisor/hypervisor-fw https://github.com/cloud-hypervisor/rust-hypervisor-firmware/releases/download/0.4.0/hypervisor-fw
-RUN curl -sLo /usr/bin/ch-remote https://github.com/cloud-hypervisor/cloud-hypervisor/releases/download/v24.0/ch-remote-static && chmod +x /usr/bin/ch-remote
+RUN set -eux; \
+    mkdir /var/lib/cloud-hypervisor; \
+    case "$(uname -m)" in \
+        'x86_64') \
+            curl -sLo /usr/bin/cloud-hypervisor https://github.com/cloud-hypervisor/cloud-hypervisor/releases/download/v24.0/cloud-hypervisor-static; \
+            curl -sLo /usr/bin/ch-remote https://github.com/cloud-hypervisor/cloud-hypervisor/releases/download/v24.0/ch-remote-static; \
+            curl -sLo /var/lib/cloud-hypervisor/hypervisor-fw https://github.com/cloud-hypervisor/rust-hypervisor-firmware/releases/download/0.4.0/hypervisor-fw; \
+            ;; \
+        'aarch64') \
+            curl -sLo /usr/bin/cloud-hypervisor https://github.com/cloud-hypervisor/cloud-hypervisor/releases/download/v24.0/cloud-hypervisor-static-aarch64; \
+            curl -sLo /usr/bin/ch-remote https://github.com/cloud-hypervisor/cloud-hypervisor/releases/download/v24.0/ch-remote-static-aarch64; \
+            curl -sLo /var/lib/cloud-hypervisor/CLOUDHV_EFI.fd https://github.com/smartxworks/cloud-hypervisor-edk2-builder/releases/download/20220706/CLOUDHV_EFI.fd; \
+            ;; \
+        *) echo >&2 "error: unsupported architecture '$(uname -m)'"; exit 1 ;; \
+    esac; \
+    chmod +x /usr/bin/cloud-hypervisor; \
+    chmod +x /usr/bin/ch-remote
 
 COPY --from=builder /workspace/main /usr/bin/virt-prerunner
 COPY build/virt-prerunner/entrypoint.sh /entrypoint.sh
